// Fill out your copyright notice in the Description page of Project Settings.


#include "PistolEnemyFSM.h"

#include "AIController.h"
#include "NavigationSystem.h"
#include "ReadyOrNot.h"
#include "Components/CapsuleComponent.h"
#include "CSW/Character/PlayerCharacter.h"
#include "CSW/Equipment/Equipment.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "HHS/PistolEnemy.h"
#include "HHS/PTEnemyAnim.h"
#include "Kismet/GameplayStatics.h"
#include "Navigation/PathFollowingComponent.h"


UPistolEnemyFSM::UPistolEnemyFSM()
{
	PrimaryComponentTick.bCanEverTick = true;
}


void UPistolEnemyFSM::BeginPlay()
{
	Super::BeginPlay();
	
	auto actor = UGameplayStatics::GetActorOfClass(GetWorld(), APlayerCharacter::StaticClass());
	target = Cast<APlayerCharacter>(actor);
	me = Cast<APistolEnemy>(GetOwner());
	anim = Cast<UPTEnemyAnim>(me->GetMesh()->GetAnimInstance());
	ai = Cast<AAIController>(me->GetController());
	if (me)
	{
		me->GetCharacterMovement()->MaxWalkSpeed = moveSpeed;
	}
	if (ai)
	{
		ai->GetPathFollowingComponent()->OnRequestFinished.AddUObject(this, &UPistolEnemyFSM::OnMoveCompleted);
	}
}


void UPistolEnemyFSM::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
	
	FString logMsg = UEnum::GetValueAsString(mState);
	GEngine->AddOnScreenDebugMessage(1, 1, FColor::Blue, logMsg);
	
	switch ( mState )
	{
	case EPTEnemyState::Idle:		{ IdleState();		}	break;
	case EPTEnemyState::Move:		{ MoveState();		}	break;
	case EPTEnemyState::Attack:		{ AttackState();	}	break;
	case EPTEnemyState::Damage:		{ DamageState();	}	break;
	case EPTEnemyState::Die:		{ DieState();		}	break;
	case EPTEnemyState::Escape:		{ EscapeState();	}	break;
	}
}

void UPistolEnemyFSM::IdleState()
{
	CurrentTime += GetWorld()->DeltaTimeSeconds;
	
	if ( CurrentTime > IdleDelayTime )
	{
		GetRandomPositionInNavMesh(me->GetActorLocation(), 500.0f, randomPos);
		mState = EPTEnemyState::Move;
		CurrentTime = 0.0f;
		anim->AnimState = mState;
		
		if (me)
		{
			me->GetCharacterMovement()->MaxWalkSpeed = moveSpeed;  // ì›ë˜ ì†ë„ë¡œ ë³µêµ¬
		}
	}
}

void UPistolEnemyFSM::MoveState()
{
	FVector destination = target->GetActorLocation();
	FVector dir = destination - me->GetActorLocation();
	
	auto ns = UNavigationSystemV1::GetNavigationSystem(GetWorld());
	
	FPathFindingQuery query;
	FAIMoveRequest req;
	
	req.SetAcceptanceRadius(3);
	req.SetGoalLocation(destination);
	ai->BuildPathfindingQuery(req, query);
	FPathFindingResult r = ns->FindPathSync(query);
	
	if (r.Result == ENavigationQueryResult::Success)
	{
		ai->MoveToLocation(destination);
	}
	else
	{
		auto result = ai->MoveToLocation(randomPos);
		if (result == EPathFollowingRequestResult::AlreadyAtGoal)
		{
			GetRandomPositionInNavMesh(me->GetActorLocation(), 500.0f, randomPos);
		}
	}
	
	if ( dir.Size() < attackRange )
	{
		ai->StopMovement();
		mState = EPTEnemyState::Attack;
		anim->AnimState = mState;
		anim->bAttackPlay = true;
		CurrentTime = attackDelayTime;
	}
}

void UPistolEnemyFSM::AttackState()
{
	CurrentTime += GetWorld()->DeltaTimeSeconds;

	if ( CurrentTime > attackDelayTime )
	{
		PRINT_LOG(TEXT("Attack~~!@~#!~#"));
		
		CurrentTime = 0.0f;
		anim->bAttackPlay = true;
		me->CombatComp->HoldingEquipment->LineTraceTarget = target->GetActorLocation();
		me->CombatComp->HoldingEquipment->BeginUse();
	}

	float distance = FVector::Distance(target->GetActorLocation(), me->GetActorLocation());
	
	if ( distance > attackRange )
	{
		GetRandomPositionInNavMesh(me->GetActorLocation(), 500.0f, randomPos);
		mState = EPTEnemyState::Move;
		anim->AnimState = mState;
	}
}

void UPistolEnemyFSM::DamageState()
{
	CurrentTime += GetWorld()->DeltaTimeSeconds;

	if ( CurrentTime > damageDelayTime )
	{
		mState = EPTEnemyState::Idle;
		CurrentTime = 0.0f;
		anim->AnimState = mState;
	}
}

void UPistolEnemyFSM::DieState()
{
//	PRINT_LOG(TEXT("ì ì´ ì‚¬ë§ ìƒíƒœë¡œ ì „í™˜"));
//
//	mState = EPTEnemyState::Die;
//	anim->AnimState = mState;
//
//	// AI ì»¨íŠ¸ë¡¤ëŸ¬ í•´ì œ
//	if (ai)
//	{
//		ai->UnPossess();
//		ai = nullptr;
//	}
//
//	// ì ì´ ë“¤ê³  ìˆë˜ ë¬´ê¸° ë“œë
//	if (me->CombatComp)
//	{
//		me->CombatComp->DropHoldingEquipment();
//	}
//	
//	// ì¶©ëŒ ì²˜ë¦¬ ë¹„í™œì„±í™” (CapsuleComponent)
//	me->GetCapsuleComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
//
//	// ì‚¬ë§ ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ
//	if (anim && anim->EnemyMontage)
//	{
//		// ìƒíƒœë¥¼ ì£½ìŒìœ¼ë¡œ ì „í™˜
//		mState = EPTEnemyState::Die;
//		me->PlayAnimMontage(anim->EnemyMontage, 1.0f, TEXT("Die"));
//		PRINT_LOG(TEXT("ì ì´ ì‚¬ë§ ì• ë‹ˆë©”ì´ì…˜ ì¬ìƒ"));
//	}
}

void UPistolEnemyFSM::EscapeState()
{
	if (bIsEscaping)
	{
		return;
	}
	bIsEscaping = true;
	PRINT_LOG(TEXT("Escape ìƒíƒœ"));

	
	// ë„ë§ ìœ„ì¹˜ ì„¤ì • (ëœë¤ or íŠ¹ì • ìœ„ì¹˜)
	escapeLocation = FVector(2126.275427f, -3586.238729f, 71.715371f); // ì˜ˆì œ ì¢Œí‘œ
	PRINT_LOG(TEXT("ë„ë§ ìœ„ì¹˜: %s"), *escapeLocation.ToString());

	// AI ì´ë™ ì‹œì‘ (í•œ ë²ˆë§Œ ì‹¤í–‰)
	if (ai)
	{
		EPathFollowingRequestResult::Type result = ai->MoveToLocation(escapeLocation);

		if (result == EPathFollowingRequestResult::Failed)
		{
			PRINT_LOG(TEXT("ë„ë§ ìœ„ì¹˜ë¡œ ì´ë™ ì‹¤íŒ¨! ìƒˆë¡œìš´ ìœ„ì¹˜ ì„¤ì •"));
			GetRandomPositionInNavMesh(me->GetActorLocation(), 1000.0f, escapeLocation);
			ai->MoveToLocation(escapeLocation);
		}
		else
		{	
			PRINT_LOG(TEXT("ì ì´ ë„ë§ ì¤‘..."));
		}
	}

	// ë„ë§ ì• ë‹ˆë©”ì´ì…˜ ì‹¤í–‰
	if (anim && anim->EnemyRun)
	{
		me->PlayAnimMontage(anim->EnemyRun, 1.0f, TEXT("Escape"));
	}
	// ì´ë™ ì†ë„ ì¦ê°€ (ì˜ˆ: ì›ë˜ ì†ë„ì˜ 3ë°°ë¡œ ì„¤ì •)
	if (me)
	{
		me->GetCharacterMovement()->MaxWalkSpeed = moveSpeed * 3.0f;  // ì´ë™ ì†ë„ë¥¼ ì¦ê°€ì‹œí‚´
	}
	anim->AnimState = mState;

	//// AIê°€ ë„ë§ ìœ„ì¹˜ì— ë„ì°©í•˜ë©´ Idle ìƒíƒœë¡œ ì „í™˜
	//if (ai->GetMoveStatus() == EPathFollowingStatus::Idle)
	//{
	//	PRINT_LOG(TEXT("ì ì´ ë„ë§ ìœ„ì¹˜ì— ë„ì°©! ëŒ€ê¸° ìƒíƒœë¡œ ì „í™˜"));
	//	mState = EPTEnemyState::Idle;
	//	anim->AnimState = mState;
	//	bIsEscaping = false;
	//}
}

void UPistolEnemyFSM::OnDamageProcess(int32 damage)
{
	hp -= damage;

	if (hp > 0) // ì‚´ì•„ ìˆì„ ë•Œë§Œ ë°˜ì‘
	{
		if (ai && target && mState != EPTEnemyState::Escape)
		{
			ai->SetFocus(target, EAIFocusPriority::Gameplay);
			PRINT_LOG(TEXT("ì ì´ í”Œë ˆì´ì–´ë¥¼ ë°”ë¼ë´„"));
		}

		// âœ… ë„ë§ ìƒíƒœê°€ í•œ ë²ˆë§Œ ì‹¤í–‰ë˜ë„ë¡ ê°œì„ 
		if (hp <= 2 && mState != EPTEnemyState::Escape && !bHasEscaped)
		{
			bHasEscaped = true;  // ğŸŸ¢ í•œ ë²ˆë§Œ ì‹¤í–‰ë˜ë„ë¡ ì„¤ì •

			mState = EPTEnemyState::Escape;
			anim->AnimState = mState;

			if (ai)
			{
				ai->ClearFocus(EAIFocusPriority::Gameplay);
				me->bUseControllerRotationYaw = false;
			}

			PRINT_LOG(TEXT("ì ì´ ë„ë§ì¹©ë‹ˆë‹¤!"));
			return;
		}
        
		mState = EPTEnemyState::Damage;
        
		int32 randValue = FMath::RandRange(0,1);
		FString sectionName = FString::Printf(TEXT("Damage%d"), randValue);
		me->PlayAnimMontage(anim->EnemyMontage, 1.0f, FName(*sectionName));
	}
	else // ì ì´ ì£½ì—ˆì„ ë•Œ
	{
		mState = EPTEnemyState::Die;
		me->PlayAnimMontage(anim->EnemyMontage, 1.0f, TEXT("Die"));
		//	// ì¶©ëŒ ì²˜ë¦¬ ë¹„í™œì„±í™” (CapsuleComponent)
     	me->GetCapsuleComponent()->SetCollisionEnabled(ECollisionEnabled::NoCollision);
		me->CombatComp->DropHoldingEquipment();
	}
	ai->StopMovement();
	anim->AnimState = mState;
	}
//	hp -= damage;
//
//	if (ai && target)
//	{
//		ai->SetFocus(target, EAIFocusPriority::Gameplay);
//		PRINT_LOG(TEXT("ì ì´ í”Œë ˆì´ì–´ë¥¼ ë°”ë¼ë´„"));
//	}
//
//	if ( hp > 0 )
//	{
//		if (hp <= 2 && mState != EPTEnemyState::Escape)
//		{
//			mState = EPTEnemyState::Escape;
//			anim->AnimState = mState;
//			PRINT_LOG(TEXT("ì ì´ ë„ë§ì¹©ë‹ˆë‹¤!"));
//			return;
//		}
//		
//		mState = EPTEnemyState::Damage;
//		
//		int32 randValue = FMath::RandRange(0,1);
//		FString sectionName = FString::Printf(TEXT("Damage%d"), randValue);
//		me->PlayAnimMontage(anim->EnemyMontage, 1.0f, FName(*sectionName));
//	}
//	else
//	{
//		mState = EPTEnemyState::Die;
//		me->PlayAnimMontage(anim->EnemyMontage, 1.0f, TEXT("Die"));
//		me->CombatComp->DropHoldingEquipment();
//	}
//	ai->StopMovement();
//	anim->AnimState = mState;


bool UPistolEnemyFSM::GetRandomPositionInNavMesh(FVector centerLocation, float radius, FVector& dest)
{
	auto ns = UNavigationSystemV1::GetNavigationSystem(GetWorld());

	FNavLocation loc;
	bool result = ns->GetRandomReachablePointInRadius(centerLocation, radius, loc);
	dest = loc.Location;
	return result;
}

void UPistolEnemyFSM::OnAttackEnd()
{
	anim->bAttackPlay = false;
}

void UPistolEnemyFSM::OnMoveCompleted(FAIRequestID RequestID, const FPathFollowingResult& Result)
{
	if (mState == EPTEnemyState::Escape)
	{
		PRINT_LOG(TEXT("ì ì´ ë„ë§ ìœ„ì¹˜ì— ë„ì°©! Idle ìƒíƒœë¡œ ì „í™˜"));

		mState = EPTEnemyState::Idle;
		anim->AnimState = mState;
		bIsEscaping = false;

		// ì›ë˜ ì´ë™ ì• ë‹ˆë©”ì´ì…˜ìœ¼ë¡œ ë³€ê²½
		if (anim && anim->EnemyWalk)
		{
			me->PlayAnimMontage(anim->EnemyWalk, 1.0f, TEXT("Walk"));
		}

		// ì´ë™ ì†ë„ë¥¼ ì›ë˜ëŒ€ë¡œ ë³µêµ¬
		if (me)
		{
			me->GetCharacterMovement()->MaxWalkSpeed = moveSpeed;
		}
	}
}